### PR TITLE
Grid & Modal Components

### PR DESCRIPTION
**Pull request by horsemaker**
- Added Grid Component
- Added Modal Component

recording

recording

### CODE REVIEW

**Review by MarkVed17 — APPROVED** [review]
Looks good to merge!

**Review by someshtiwarii — APPROVED** [review]
Clean UI ! Good to merge !

**Review by msdeshmukh009 — APPROVED** [review]
Looks good to me.

**Review by Chakravarthi0 — APPROVED** [review]
looks good

**Pull request merged**
