### PR TITLE
Alert & Button Components

### PR DESCRIPTION
**Pull request by horsemaker**
Added the alert & button components to the component library.

### CODE REVIEW

**Review by manojasarsa — APPROVED** [review]
Looks clean!👍

**Review by tanveertkd — APPROVED** [review]
This looks good.
Just a quick suggestion though, it seems like most of your component styles are coming from main.css. It would be much easier to maintain later on if you separate them out into their own separate files and import them onto the main.css file.

**Comment by horsemaker** [comment]
> This looks good. Just a quick suggestion though, it seems like most of your component styles are coming from main.css. It would be much easier to maintain later on if you separate them out into their own separate files and import them onto the main.css file.

damn, you caught me! 👀
I actually write the component styling first in different CSS files. In the end, I copy them in main.css. Am actually confused between importing or copying them directly. 🤔

**Review by vijaytembugade — APPROVED** [review]
Looks clean. Good to go 😉

**Comment by narharikale** [comment]
same suggestion as @tanveertkd mentioned otherwise ready to go ✔

**Review by MarkVed17 — APPROVED** [review]
These are really nice Alerts & Buttons 👍🏼

**Pull request merged**
