### PR TITLE
Landing page

### PR DESCRIPTION
**Pull request by horsemaker**
landing page with dummy component sections.

### CODE REVIEW

**Comment by vijaytembugade** [comment]
Amazing concept. 
Background color looks pretty good,
You can use Modal or pop-ups to show component, just suggestion

**Comment by AtulHande03a** [comment]
Very well used colors and the design is simple yet elegant. Appealing to the eye. Realy well made. Also it is looking good in mobile view. Kudos to this !!✨

**Comment by MarkVed17** [comment]
Viewing it on my mobile rn, the layout is pretty clean I’d say. Also, good taste on colors there. So far, so good.

**Comment by narharikale** [comment]
Elegant colors👌  and eye-soothing

**Comment by t007rushi** [comment]
looks awesome use of responsiveness, can add more breakpoints as you go-ahead

**Review by vijaytembugade — APPROVED** [review]

**Review by AtulHande03a — APPROVED** [review]
The landing page looks good.

**Pull request merged**
